name: build-and-test

on:
  push:
    branches: [master]
  schedule:
    - cron: '*/15****'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Build server
        uses: ./build_server.sh

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: ./test_server.sh
